//This function generates a random number between 0 (inclusive) and 1 (exclusive), multiplies the number by the difference between the maximum and minimum, then adds 1 to determine the possible outcomes between the minimum and maximum, and adds the minimum to ensure that the lowest random number generated by the function is the minimum value and the highest random number generated by the function is the maximum value
function getRandomInteger(min, max) {
	return Math.floor(Math.random() * (max - min + 1)) + 1;
}

//This function stores the generated positive integer of the getRandomInteger function to an array
function getArray() {
	var randomInt = []
	for (var i = 0; i < 8; i++) {
		randomInt.push(getRandomInteger(min, max))
	}
	return randomInt
}

//This function iterates through each element of the randomInt array, checking if it meets the conditions. If it does, it is added to a new array; if it does not, iteration continues until the final element is checked.
function checkCondition(integer) {
	var newRandomInt = [];
	for (var iterator = 0; iterator < integer.length; iterator++) {
		if ((integer[iterator] % 3 == 0) || (integer[iterator] % 2 == 0 && integer[iterator] % 4 != 0)) {
			newRandomInt.push(integer[iterator])
		}
	}
	return newRandomInt
}

//This section is a variable assignment of the minimum and maximum values on which the function's inputs will be based.
var min = 1 //since the lowest positive integer is 1
var max = 100

var input = getArray()

//This section is in charge of presenting the return values of functions.
console.log('Input:', input)
console.log('Output:', checkCondition(input))
